### ISSUE TITLE
Travis failing frequently

### ISSUE THREAD

**Issue by AbdealiJK** [idiap/bob#221]
I noticed that travis is frequently failing. In fact last 5 travis builds on master has been failing. Branches for v2.2.0 and 2.0.7 are failing too (Reference: https://travis-ci.org/idiap/bob/branches)

As pypi uses 2.2.0, it would be encouraging to have travis successful for atleast that branch if not master too.

I checked out the logs, and it seems to be because travis is timing out or something ?

**Comment by tiagofrepereira2012** [comment]
Hi  AbdealiJK,

For the open source travis we have 50 minutes to finish the builds and since Bob has several dependencies to be built (bob.*), we see very often these timeouts.
To speed up the build time we store the wheels for every dependency in our server (https://www.idiap.ch/software/bob/wheels/travis/), but for this particular build we don't have yet the wheels for Python 3.5, that's why this particular build failed.

Once we have the wheels for python 3.5, everything will be green again.
